# Default values for docker-app.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image:
  repository: docker.artifactory/docker-app
  tag: latest
  secretName: regsecret
  pullPolicy: Always

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer
  port: 8181
  targetPort: 80
  nodePort: ""

resources: {}

nodeSelector: {}